from pathlib import Path
import csv
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "examples" / "public_research_snapshot_v4_3.csv"
FIGURE = ROOT / "figures" / "shockbridge_regime_question_map.svg"

FORBIDDEN_TERMS = [
    "METHODOLOGY_LOCK",
    "PRIVATE_CODE_AUDIT",
    "macro_confirmed_action_policy",
    "HEDGE_REVIEW",
    "official_macro_and_gold_anchor",
    "LBMA_GOLD_AM_LOCAL",
    "ml_walk_forward",
    "mcca_block_contribution",
    "FRED_API_KEY",
    "NASDAQ_DATA_LINK_API_KEY",
    "1b9e10b0",
]


def read_snapshot_meta():
    if not SNAPSHOT.exists():
        return 0, 0, "public snapshot not found"

    with SNAPSHOT.open("r", encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        columns = reader.fieldnames or []
        rows = list(reader)

    return len(columns), len(rows), SNAPSHOT.name


def build_public_question_graphic():
    FIGURE.parent.mkdir(parents=True, exist_ok=True)

    n_cols, n_rows, snapshot_name = read_snapshot_meta()
    generated = datetime.utcnow().strftime("%Y-%m-%d UTC")

    svg = f'''<svg width="1600" height="980" viewBox="0 0 1600 980" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#070B16"/>
      <stop offset="48%" stop-color="#0E1730"/>
      <stop offset="100%" stop-color="#111827"/>
    </linearGradient>

    <linearGradient id="blue" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#1D4ED8"/>
      <stop offset="100%" stop-color="#60A5FA"/>
    </linearGradient>

    <linearGradient id="gold" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#F59E0B"/>
      <stop offset="100%" stop-color="#FDE68A"/>
    </linearGradient>

    <linearGradient id="red" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#7F1D1D"/>
      <stop offset="100%" stop-color="#FB7185"/>
    </linearGradient>

    <filter id="shadow">
      <feDropShadow dx="0" dy="12" stdDeviation="18" flood-color="#000000" flood-opacity="0.45"/>
    </filter>

    <marker id="arrow" markerWidth="16" markerHeight="16" refX="13" refY="8" orient="auto">
      <path d="M2,2 L14,8 L2,14 Z" fill="#93C5FD"/>
    </marker>
  </defs>

  <rect width="1600" height="980" fill="url(#bg)"/>

  <text x="800" y="70" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="42" font-weight="800" fill="#FFFFFF">
    When Does a Market Shock Become a Regime Problem?
  </text>

  <text x="800" y="112" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="20" fill="#BFD0EA">
    A public-safe ShockBridge evidence map: from isolated movement to regime-relevant transmission
  </text>

  <text x="800" y="146" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="15" fill="#8EA4C8">
    This figure is generated by the public pipeline and does not disclose private thresholds, weights, proprietary diagnostics, or action rules.
  </text>

  <!-- Main spine -->
  <line x1="170" y1="365" x2="1430" y2="365" stroke="#334155" stroke-width="8" stroke-linecap="round"/>
  <line x1="190" y1="365" x2="1410" y2="365" stroke="#93C5FD" stroke-width="3" stroke-linecap="round" stroke-dasharray="14 16"/>

  <!-- Nodes -->
  <g font-family="Arial, Helvetica, sans-serif" filter="url(#shadow)">
    <circle cx="190" cy="365" r="62" fill="#111827" stroke="#60A5FA" stroke-width="4"/>
    <text x="190" y="352" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">1</text>
    <text x="190" y="380" text-anchor="middle" font-size="15" fill="#DCE8FF">Shock</text>

    <circle cx="440" cy="365" r="62" fill="#111827" stroke="#60A5FA" stroke-width="4"/>
    <text x="440" y="352" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">2</text>
    <text x="440" y="380" text-anchor="middle" font-size="15" fill="#DCE8FF">Transmission</text>

    <circle cx="690" cy="365" r="62" fill="#111827" stroke="#FBBF24" stroke-width="4"/>
    <text x="690" y="352" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">3</text>
    <text x="690" y="380" text-anchor="middle" font-size="15" fill="#FFECC0">Persistence</text>

    <circle cx="940" cy="365" r="62" fill="#111827" stroke="#FBBF24" stroke-width="4"/>
    <text x="940" y="352" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">4</text>
    <text x="940" y="380" text-anchor="middle" font-size="15" fill="#FFECC0">Confirmation</text>

    <circle cx="1190" cy="365" r="62" fill="#111827" stroke="#FB7185" stroke-width="4"/>
    <text x="1190" y="352" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">5</text>
    <text x="1190" y="380" text-anchor="middle" font-size="15" fill="#FFD5DD">Validation</text>

    <circle cx="1410" cy="365" r="70" fill="#111827" stroke="#FB7185" stroke-width="5"/>
    <text x="1410" y="352" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">6</text>
    <text x="1410" y="380" text-anchor="middle" font-size="15" fill="#FFD5DD">Regime Risk</text>
  </g>

  <!-- Question cards -->
  <g font-family="Arial, Helvetica, sans-serif" filter="url(#shadow)">
    <rect x="80" y="500" rx="22" width="220" height="150" fill="#0F172A" stroke="#1D4ED8" stroke-width="2"/>
    <text x="190" y="535" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">Is it just noise?</text>
    <text x="190" y="570" text-anchor="middle" font-size="14" fill="#C7D2FE">A price move alone</text>
    <text x="190" y="592" text-anchor="middle" font-size="14" fill="#C7D2FE">does not define</text>
    <text x="190" y="614" text-anchor="middle" font-size="14" fill="#C7D2FE">a regime problem.</text>

    <rect x="330" y="500" rx="22" width="220" height="150" fill="#0F172A" stroke="#1D4ED8" stroke-width="2"/>
    <text x="440" y="535" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">Is it spreading?</text>
    <text x="440" y="570" text-anchor="middle" font-size="14" fill="#C7D2FE">Evidence matters when</text>
    <text x="440" y="592" text-anchor="middle" font-size="14" fill="#C7D2FE">stress crosses markets,</text>
    <text x="440" y="614" text-anchor="middle" font-size="14" fill="#C7D2FE">not only headlines.</text>

    <rect x="580" y="500" rx="22" width="220" height="150" fill="#0F172A" stroke="#F59E0B" stroke-width="2"/>
    <text x="690" y="535" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">Does it persist?</text>
    <text x="690" y="570" text-anchor="middle" font-size="14" fill="#FDE68A">A temporary spike is</text>
    <text x="690" y="592" text-anchor="middle" font-size="14" fill="#FDE68A">not the same as</text>
    <text x="690" y="614" text-anchor="middle" font-size="14" fill="#FDE68A">regime pressure.</text>

    <rect x="830" y="500" rx="22" width="220" height="150" fill="#0F172A" stroke="#F59E0B" stroke-width="2"/>
    <text x="940" y="535" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">Is it confirmed?</text>
    <text x="940" y="570" text-anchor="middle" font-size="14" fill="#FDE68A">Macro, curve, credit,</text>
    <text x="940" y="592" text-anchor="middle" font-size="14" fill="#FDE68A">FX, and commodities</text>
    <text x="940" y="614" text-anchor="middle" font-size="14" fill="#FDE68A">must be separated.</text>

    <rect x="1080" y="500" rx="22" width="220" height="150" fill="#0F172A" stroke="#FB7185" stroke-width="2"/>
    <text x="1190" y="535" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">Is it robust?</text>
    <text x="1190" y="570" text-anchor="middle" font-size="14" fill="#FECACA">Validation protects</text>
    <text x="1190" y="592" text-anchor="middle" font-size="14" fill="#FECACA">against leakage,</text>
    <text x="1190" y="614" text-anchor="middle" font-size="14" fill="#FECACA">overfit, and narrative.</text>

    <rect x="1330" y="500" rx="22" width="220" height="150" fill="#0F172A" stroke="#FB7185" stroke-width="2"/>
    <text x="1440" y="535" text-anchor="middle" font-size="17" font-weight="800" fill="#FFFFFF">Answer</text>
    <text x="1440" y="570" text-anchor="middle" font-size="14" fill="#FECACA">A shock becomes</text>
    <text x="1440" y="592" text-anchor="middle" font-size="14" fill="#FECACA">regime-relevant only</text>
    <text x="1440" y="614" text-anchor="middle" font-size="14" fill="#FECACA">after evidence aligns.</text>
  </g>

  <!-- Bottom evidence panel -->
  <g font-family="Arial, Helvetica, sans-serif" filter="url(#shadow)">
    <rect x="170" y="725" rx="26" width="1260" height="145" fill="#101827" stroke="#334155" stroke-width="2"/>
    <text x="800" y="765" text-anchor="middle" font-size="24" font-weight="800" fill="#FFFFFF">Public Evidence Layer Generated by the Repository</text>

    <text x="260" y="810" text-anchor="middle" font-size="15" fill="#CBD5E1">Snapshot</text>
    <text x="260" y="835" text-anchor="middle" font-size="13" fill="#93C5FD">{snapshot_name}</text>

    <text x="520" y="810" text-anchor="middle" font-size="15" fill="#CBD5E1">Public Rows</text>
    <text x="520" y="835" text-anchor="middle" font-size="13" fill="#93C5FD">{n_rows}</text>

    <text x="780" y="810" text-anchor="middle" font-size="15" fill="#CBD5E1">Public Columns</text>
    <text x="780" y="835" text-anchor="middle" font-size="13" fill="#93C5FD">{n_cols}</text>

    <text x="1040" y="810" text-anchor="middle" font-size="15" fill="#CBD5E1">Generated Output</text>
    <text x="1040" y="835" text-anchor="middle" font-size="13" fill="#93C5FD">brief + question map</text>

    <text x="1300" y="810" text-anchor="middle" font-size="15" fill="#CBD5E1">Generated</text>
    <text x="1300" y="835" text-anchor="middle" font-size="13" fill="#93C5FD">{generated}</text>
  </g>

  <text x="800" y="930" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="15" fill="#94A3B8">
    Rodolfo Pereira · www.shockbridgepulse.com · rolffcoelho@hotmail.com · © 2026 Rodolfo P.
  </text>
</svg>'''

    for term in FORBIDDEN_TERMS:
        if term in svg:
            raise ValueError(f"Forbidden private term leaked into public graphic: {term}")

    FIGURE.write_text(svg, encoding="utf-8")
    return FIGURE


if __name__ == "__main__":
    output = build_public_question_graphic()
    print(f"Generated public question graphic: {output}")
